# -*- coding: utf-8 -*-

"""
    apimaticcalculatorlib.apimatic_calculator_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .controllers.simple_calculator_controller import SimpleCalculatorController

class APIMATICCalculatorClient(object):

    @lazy_property
    def simple_calculator(self):
        return SimpleCalculatorController()



